#! /bin/sh

bspc monitor -d I II III IV V

bspc config top_padding 15

#bspc config border_width           2
#bspc config window_gap             10
#bspc config split_ratio            0.50
#bspc config focus_follows_pointer  false
#bspc config borderless_monocle     true
#bspc config gapless_monocle        true
#bspc config auto_cancel            true
#bspc config auto_alternate         false
#bspc config ignore_ewmh_focus      true
#
##bspc config focused_border_color          "#917154"
##bspc config focused_border_color          "#BF3F34"
#bspc config focused_border_color          "#989584"
#bspc config normal_border_color           "#121212"
#bspc config urgent_border_color           "#EF545F"
##bspc config presel_border_color           "#705D22"
##bspc config focused_private_border_color  "#88a1ba"
##bspc config active_private_border_color   "#88a1ba"
##bspc config normal_private_border_color   "#627a92"

#### Fonts set here
##      /etc/profile.d/infinality-settings.sh
####
bspc config split_ratio         0.50
bspc config border_width        1
bspc config window_gap          10
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer false
bspc config auto_alternate true
bspc config auto_cancel true
bspc config normal_border_color "#504339"
bspc config active_border_color "#504339"
bspc config focused_border_color "#817267"
bspc config presel_border_color "#9a875f"
bspc config urgent_border_color "#504339"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1

panel &
tint2 &
