#! /bin/sh

#### Fonts set here
#/etc/profile.d/infinality-settings.sh
####

sxhkd &

bspc config split_ratio         0.50
bspc config border_width        6
bspc config window_gap          8
bspc config borderless_monocle  false
bspc config gapless_monocle     true
bspc config focus_follows_pointer false
bspc config click_to_focus any
bspc config swallow_first_click false
bspc config initial_polarity "second_child"

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config normal_border_color "#504339"   # grey
bspc config active_border_color "#2aa198"   # cyan
bspc config focused_border_color "#859900"   # green
bspc config presel_border_color "#268bd2"  # blue
bspc config urgent_border_color "#dc322f"   # red

# Only set desktops after running configs, so that the ones that
# set defaults (ex. border_width and window gap) get applied

bspc monitor -f west
bspc monitor -n '<--'
bspc monitor -d I II III IV V
bspc config -m '<--' top_padding 40

bspc monitor -f east
bspc monitor -n '-->'
bspc monitor -d VI VII VIII IX X

bspc rule -a "*:Skype" desktop=V follow=off
bspc rule -a "*:Gimp" state=floating
bspc rule -a "*:LoL Patcher" state=floating
bspc rule -a "*:LoLClient.exe" state=floating
bspc rule -a "*:nautilus" state=floating
bspc rule -a "Steam" desktop=X follow=off state=floating
bspc rule -a "Steam" desktop=X follow=off state=floating
bspc rule -a "*:Spotify" desktop=V follow=off
bspc rule -a "*:feh" state=floating

# KDE
bspc rule -a plasmashell state=floating border=off layer=normal
bspc rule -a krunner state=floating border=off
bspc rule -a kmail desktop=IV

#### COMMON
/usr/lib/kdeconnectd &
sleep 1
/usr/bin/indicator-kdeconnect &
#thunderbird &

###### BAREBONES###
xautolock -time 15 -locker '/usr/local/bin/lock' &
dunst &
$HOME/.config/polybar/launch.sh &

