#! /bin/sh

#### Fonts set here
#/etc/profile.d/infinality-settings.sh
####

#xrandr --output VGA-0 --auto --output HDMI-0 --auto --right-of VGA-0

sleep 1

sxhkd &

bspc config split_ratio         0.50
bspc config border_width        6
bspc config window_gap          8
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer false
bspc config click_to_focus true
bspc config auto_alternate true
bspc config auto_cancel true
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config normal_border_color "#504339"   # grey
bspc config active_border_color "#2aa198"   # cyan
bspc config focused_border_color "#859900"   # green
bspc config presel_border_color "#268bd2"  # blue
bspc config urgent_border_color "#dc322f"   # red


bspc monitor -f VGA-0
bspc monitor -n 'LEFT'
bspc monitor -d I II III IV V
#bspc config -m focused top_padding 30

bspc monitor -f HDMI-0 
bspc monitor -n 'RIGHT'
bspc monitor -d VI VII VIII IX X
#bspc config -m focused top_padding 0

# Only set desktops after running configs, so that the ones that
# set defaults (ex. border_width and window gap) get applied
sleep 1

bspc rule -a xfce4-session floating=on fullscreen=on
bspc rule -a xfce4-panel floating=on manage=off
bspc rule -a "Skype" desktop=X follow=off
bspc rule -a "Slack" desktop=IV follow=off
bspc rule -a "*:nautilus" state=floating
bspc rule -a "*:bzr" state=floating
bspc rule -a "Thunderbird" state=floating
bspc rule -a "Meld" state=floating
bspc rule -a "Spotify" state=floating destop=X follow=off

$HOME/.config/polybar/launch.sh
xautolock -time 15 -locker '/home/craig/my_settings/locker.sh' &
slack &
skype &
thunderbird &
dunst &
notify-send "Startup Complete"

 
