# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = [
        "xhci_pci"
        "ahci"
        "usbhid"
        "usb_storage"
        "sd_mod"
      ];
      kernelModules = [ ];
    };
    kernelPackages = pkgs.linuxPackages_6_6;
    kernelModules = [ "kvm-intel" ];
    # GPU transcoding
    kernelParams = [
      "i915.enable_guc=2"
    ];
    extraModulePackages = [ ];
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/7d1d782e-2068-46be-98a8-374ab30c28a7";
      fsType = "ext4";
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/07D0-A352";
      fsType = "vfat";
      options = [
        "fmask=0022"
        "dmask=0022"
      ];
    };

    "/mnt/camera" = {
      device = "trunas.localdomain:/mnt/mediapool/camera ";
      fsType = "nfs";
    };
    "/mnt/movies" = {
      device = "trunas.localdomain:/mnt/mediapool/media/one/hl-media/movies";
      fsType = "nfs";
    };
    "/mnt/tvshows" = {
      device = "trunas.localdomain:/mnt/mediapool/media/one/hl-media/tvshows";
      fsType = "nfs";
    };
    "/mnt/actualbudget" = {
      device = "trunas.localdomain:/mnt/mainpool/kubernetes/actualbudget";
      fsType = "nfs";
    };
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
