keys:
  - &craig_virtnix age1vj946f97ggdr053zuc9ur6z7ruzc9724pjdjvuvfrh7cx66jgy3s9eay0h
  - &craig_virtnix2 age154d4qygfmgeyx35jfexlu4j475fnpafmr9xwpthcrzsfmqq3usashqwe87
  - &craig_nixostest age1yc58hyvpxv3yny48cxcpzpk00mrgur3lhkmqvqnzhetddp65xvjq6mr2cn
  - &craig_carbonnix age1qqynfut5y2mk4v33jpcf0r4gaca6ydy3aqkc9ldm4g2ru6mhgyrqvvefu7
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *craig_virtnix
      - *craig_virtnix2
      - *craig_nixostest
      - *craig_carbonnix
