set shell := ["zsh", "-uc"]
#nix run home-manager/master -- switch --flake .#craig@hyperarch

hostname := `cat /etc/hostname`

default:
  just --list

switch-os:
    sudo nixos-rebuild switch --flake .#{{hostname}}

switch-hm target=hostname:
    home-manager switch --flake .#craig@{{target}}

get-age-key server:
    nix shell 'nixpkgs#ssh-to-age' --command  sh -c "ssh-keyscan {{server}} | ssh-to-age"

ignore-secrets:
    git update-index --skip-worktree secrets/os-secrets.yaml

reset-secrets:
    git update-index --no-skip-worktree secrets/os-secrets.yaml

gc:
    sudo nix store gc --debug
