set shell := ["zsh", "-uc"]
#nix run home-manager/release-24.11 -- switch --flake .#craig@hyperarch

hostname := `cat /etc/hostname`

default:
  just --list

old-switch-os:
    sudo nixos-rebuild switch --flake .#{{hostname}}
switch-os:
    nh os switch .

old-switch-boot-os:
    sudo nixos-rebuild boot --flake .#{{hostname}}

switch-boot-os:
    nh os boot .

switch-os-dry-run:
    sudo nixos-rebuild dry-activate --flake .#{{hostname}}

old-switch-hm target=hostname:
    home-manager switch --flake .#craig@{{target}}

#[ "{{target}}" = "beelink" ] && nh home switch . -c conrun@{{target}}
switch-hm target=hostname:
    nh home switch . -c craig@{{target}}

flake-update:
    nix flake update

flake-update-single input:
    nix flake update {{input}}

get-age-key server:
    nix shell 'nixpkgs#ssh-to-age' --command  sh -c "ssh-keyscan {{server}} | ssh-to-age"

ignore-secrets:
    git update-index --skip-worktree secrets/os-secrets.yaml; git update-index --skip-worktree secrets/ca.crt

reset-secrets:
    git update-index --no-skip-worktree secrets/os-secrets.yaml; git update-index --no-skip-worktree secrets/ca.crt

gc:
    sudo nix store gc --debug
